# Generated by Django 3.2.11 on 2022-01-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admirer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='secret_message',
            new_name='Secret_Messages',
        ),
    ]
